name: flutter_hooks_lint_plugin_loader
description: bootstrap package of flutter_hooks_lint_plugin
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_hooks_lint_plugin:
    git:
      url: https://github.com/mj-hd/flutter_hooks_lint_plugin
      ref: 81d119ba777c8a9b4b215b7cab0f84294da16a7d

