name: flutter_hooks_lint_plugin_loader
description: bootstrap package of flutter_hooks_lint_plugin
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_hooks_lint_plugin: ^0.0.1
